
const GET_DISHES = 'GET_DISHES';
const GET_DISHES_SUCCESS = 'GET_DISHES_SUCCESS';
const GET_DISHES_FAILURE = 'GET_DISHES_FAILURE';

const DETAIL_DISH = 'DETAIL_DISH';

export { GET_DISHES, GET_DISHES_SUCCESS, GET_DISHES_FAILURE, DETAIL_DISH };