
const DETAIL_DISH = 'DETAIL_DISH';
const GET_DISHES = 'GET_DISHES';
const GET_DISHES_SUCCESS = 'GET_DISHES_SUCCESS';
const GET_DISHES_FAILURE = 'GET_DISHES_FAILURE';

export { DETAIL_DISH, GET_DISHES, GET_DISHES_SUCCESS, GET_DISHES_FAILURE };